### ISSUE TITLE
Getting Error while Installation : useLocation() may be used only in the context of a Router component

### ISSUE THREAD

**Issue by jaya-official** [OpsLevel/backstage-plugin#33]
Hi,
I tried installing this plugin by following the steps mentioned here: [https://github.com/OpsLevel/backstage-plugin](url)
After I added all the configurations and started the backstage-app, I got this error:
<img width="341" alt="image" src="https://github.com/OpsLevel/backstage-plugin/assets/140375332/37c2f58f-eba7-4bb7-8566-b65f60125215">
When I tried to check which configuration step is causing this error, I realized this error prompts as soon as I added this plugin using below command:
```
yarn add --cwd packages/app backstage-plugin-opslevel-maturity
``` 
Please, let me if I am missing something @patrick-th @sabeerzaman  and @sergio-opslevel.

**Comment by katerberg** [comment]
Sorry for the late reply, our auto-sync of issues to Slack was broken so we missed this.

It looks like maybe this stop got missed: https://github.com/OpsLevel/backstage-plugin#add-route--global-nav

The Backstage Plugin assumes that it lives inside the router, so it's possible that if you're trying to run it from outside of one that it will fail to load.

If you have an example repository with it failing, I'd be happy to take a look at the configuration to see if this is potentially a bug, but it's very hard to diagnose without a sample failing project.

Alternatively, if you reach out to your OpsLevel Customer Success Manager, they can help walk you through the steps to ensure this is set up in your organization.

**Comment by siddharth159** [comment]
Hi @katerberg we have validated the steps, and all are ok. could you please help us which files you required to debug the issue.

**Comment by jaya-official** [comment]
Hi @katerberg,
Thank you for your response, it worked for us after we re-installed the node-modules, it was some node-modules version issue.

**Comment by katerberg** [comment]
Glad to hear it! I'll close this one now then.
